"""empty message

Revision ID: daf964ec8088
Revises: 
Create Date: 2020-02-29 17:36:13.002260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf964ec8088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artistName', sa.String(length=100), nullable=True),
    sa.Column('style', sa.Integer(), nullable=True),
    sa.Column('imgURL', sa.String(length=100), nullable=True),
    sa.Column('isHot', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('songName', sa.String(length=100), nullable=True),
    sa.Column('singer', sa.String(length=100), nullable=True),
    sa.Column('fileURL', sa.String(length=100), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('style', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collect')
    op.drop_table('user')
    op.drop_table('song')
    op.drop_table('artist')
    # ### end Alembic commands ###
